### ISSUE TITLE
byFunction loses data

### ISSUE THREAD

**Issue by bebraw** [sorensen/absolutify#2]
Hi,

Given the following script

``` javascript
var _url = require('url');
var absolutify = require('absolutify');

var baseUrl = 'http://demo.com';
var content = '<a href="../../blog/demo-interview">check out</a></p>';

console.log(resolveUrls(baseUrl, content));

function resolveUrls (baseUrl, content) {
  return absolutify(content, function (url, attrName) {
    if (attrName === 'href') {
      console.log('resolving', _url.resolve(baseUrl, url), baseUrl, url);
      return _url.resolve(baseUrl, url);
    }

    return url;
  });
}
```

I get output

``` bash
resolving http://demo.com/ http://demo.com ../..
<a href="http://demo.com//blog/demo-interview">check out</a></p>
```

Shouldn't `url` point to `../../blog/demo-interview` instead of just `../..`?

**Comment by bebraw** [comment]
I hacked around it like this:

``` javascript
function resolveUrls (baseUrl, content) {
  return absolutify(content, function (url, attrName) {
    if (attrName === 'href') {
      return _.trimEnd(_url.resolve(baseUrl, url), '/');
    }

    return url;
  });
}
```

So looks like the function gets just a fragment. It might be better if it got it all.

**Comment by sorensen** [comment]
@bebraw I agree that the method should get more data, I don't know how to actually make that work though given the RegExp used.

What is the end result you are trying to achieve here?

``` js
absolutify(content, function(url, attr) {
  return baseUrl + '/' + url
})
```

Would return the following: 

``` html
<a href="http://demo.com/../../blog/demo-interview">check out</a></p>
```

**Comment by bebraw** [comment]
Hi,

It's a part of my [rss plugin](https://github.com/antwarjs/rss-plugin). I convert all links to absolute. So this particular link should resolve as `http://demo.com/blog/demo-interview`.

That url is actually a little sketchy with those `..`'s and I probably should fix them up on my side. I'm ok with `wontfix`.

**Comment by sorensen** [comment]
This one is only particularly odd because that URL would not resolve against that base as it is trying to go above the root.  

If the base URL was something like `http://foo.com/one/two/` then the `../../` would be ok.

**Comment by bebraw** [comment]
That's right. I think I'll fix up my links. 👍

**Comment by sorensen** [comment]
Sounds good, will close this one out then.
